In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("/content/project_data_cleaned_v1.csv")
data.head()

,comment_id,text,published_at,roberta_neg,roberta_neu,roberta_pos,roberta_label,num_words
0,UgwoiJ6zDlEHgNHbKHl4AaABAg,mike is the most traumatic in this season his ...,2025-12-27T02:17:44Z,0.971900,0.025935,0.002164,negative,42
1,UgyXJRcSbn74ajhkmBN4AaABAg,"this was so bad yall. wth was that writing, th...",2025-12-27T02:13:56Z,0.975026,0.022050,0.002924,negative,54
2,UgzhXrqNFCkMLMOB6dh4AaABAg,not a single shot from final episode,2025-12-27T01:51:33Z,0.390147,0.579394,0.030459,neutral,7
3,UgxQPzUbRC8ECcXroFF4AaABAg,rated j for jesus: a box office blasphemy – ho...,2025-12-27T01:35:21Z,0.299472,0.592630,0.107898,neutral,15
4,UgzQIyIMuD3WZha30dd4AaABAg,does hollyweird ever stop attacking christiani...,2025-12-27T01:30:37Z,0.972716,0.024830,0.002454,negative,27

In [3]:
data = data.loc[:,["text", "roberta_label"]].rename(columns={"roberta_label" : "label"})

In [4]:
data.shape

(19596, 2)

In [6]:
# preprocessing text
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Ensure NLTK data is downloaded
nltk.download('stopwords')
nltk.download('wordnet')

# Preprocessing function
def preprocess_comment(comment):
    comment = comment.lower().strip()
    comment = re.sub(r'\n', ' ', comment)
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])
    return comment

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

In [8]:
data["text"] = data["text"].apply(preprocess_comment)

In [10]:
def encode_label(string):
  """takes a sentiment label and converts it to 0 if neutral, 1 if positive and -1 if negative"""
  if string == "positive":
    return 1
  elif string == "negative":
    return -1
  else:
    return 0

data["label"] = data["label"].apply(encode_label)

In [11]:
data.sample(10)

                                                    text  label
3613   two type audience comment section 1.who threat...     -1
3080   volume 2?!are telling year waiting release fin...      0
14818                                           let gooo      1
3278                            120 actually insaneeeeee      1
9037                         max better make alive istg.      0
5591                                           cant wait      1
16861                           please save steve dustin      0
7619      nooo, another trailer without confirming billy     -1
16678  134 let goo shock jock theory debunkedit fores...      0
2123                       like comment byler button lol      0

In [13]:
data.to_csv("data_for_model_building.csv", index=False)

In [14]:
#  splitting data into X and y
X = data.loc[:, "text"]
y = data.loc[:, "label"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Vectorizing using Tfidf

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [17]:
# TF-IDF vectorizer with max 10,000 features (fit only on X_train)
vectorizer_tfidf = TfidfVectorizer(max_features=10000)
X_train_tfidf = vectorizer_tfidf.fit_transform(X_train)
X_test_tfidf = vectorizer_tfidf.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import precision_score, recall_score, f1_score
from tqdm import tqdm

In [24]:
# Define classifiers
classifiers = {
    "Naive Bayes": MultinomialNB(),
    "Random Forest": RandomForestClassifier(random_state=42, n_estimators=200)
}

# Evaluate classifiers with tqdm
results = []

for name, clf in tqdm(classifiers.items(), desc="Evaluating classifiers"):
    clf.fit(X_train_tfidf, y_train)
    y_pred = clf.predict(X_test_tfidf)
    results.append({
        "Model": name,
        "Precision (macro)": precision_score(y_test, y_pred, average='macro', zero_division=0),
        "Recall (macro)": recall_score(y_test, y_pred, average='macro', zero_division=0),
        "F1 Score (macro)": f1_score(y_test, y_pred, average='macro', zero_division=0)
    })

# Convert to DataFrame
results_df = pd.DataFrame(results)
print(results_df)

# Optional: map predictions back to original labels
# y_pred_original = le.inverse_transform(y_pred)

Evaluating classifiers: 100%|██████████| 2/2 [02:03<00:00, 61.83s/it]

           Model  Precision (macro)  Recall (macro)  F1 Score (macro)
0    Naive Bayes           0.666360        0.638870          0.642179
1  Random Forest           0.672807        0.676288          0.674014

In [26]:
results_df

           Model  Precision (macro)  Recall (macro)  F1 Score (macro)
0    Naive Bayes           0.666360        0.638870          0.642179
1  Random Forest           0.672807        0.676288          0.674014

In [28]:
# Encode labels to 0,1,2 for XGBoost and LightGBM
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test) # -1->0, 0->1, 1->2

In [31]:
# Only XGBoost and LightGBM
classifiers = {
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42),
    "LightGBM": LGBMClassifier(random_state=42)
}

# Evaluate classifiers with tqdm
results = []

for name, clf in tqdm(classifiers.items(), desc="Evaluating LightGBM & XGBoost"):
    clf.fit(X_train_tfidf, y_train_encoded)
    y_pred = clf.predict(X_test_tfidf)
    results.append({
        "Model": name,
        "Precision (macro)": precision_score(y_test_encoded, y_pred, average='macro', zero_division=0),
        "Recall (macro)": recall_score(y_test_encoded, y_pred, average='macro', zero_division=0),
        "F1 Score (macro)": f1_score(y_test_encoded, y_pred, average='macro', zero_division=0)
    })

# Separate results DataFrame
results_df_lightgbm_xgb = pd.DataFrame(results)
results_df_lightgbm_xgb

Evaluating LightGBM & XGBoost:   0%|          | 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [22:51:54] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
Evaluating LightGBM & XGBoost:  50%|█████     | 1/2 [00:18<00:18, 18.27s/it]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.110743 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 19135
[LightGBM] [Info] Number of data points in the train set: 15676, number of used features: 639
[LightGBM] [Info] Start training from score -0.960038
[LightGBM] [Info] Start training from score -1.051573
[LightGBM] [Info] Start training from score -1.317761

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
Evaluating LightGBM & XGBoost: 100%|██████████| 2/2 [00:21<00:00, 10.92s/it]

      Model  Precision (macro)  Recall (macro)  F1 Score (macro)
0   XGBoost           0.715323        0.678288          0.686064
1  LightGBM           0.697441        0.671406          0.678072

- Out of Multinomial Naive bayes, Random Forest, xgboost and lightgbm, xgboost seems to perform best in terms of all given metrics.

### Hyperparamter tuning on Xgboost, random forest and light gbm

In [33]:
! pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.2)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.45)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 8.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [35]:
# Random forest hyperparameter tuning
import optuna


def objective_rf(trial):
    # Hyperparameter search space
    n_estimators = trial.suggest_int('n_estimators', 50, 500)
    max_depth = trial.suggest_int('max_depth', 2, 30)
    min_samples_split = trial.suggest_int('min_samples_split', 2, 20)
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 20)
    max_features = trial.suggest_categorical('max_features', ['sqrt', 'log2', None])


    clf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        random_state=42
    )

    clf.fit(X_train_tfidf, y_train_encoded)
    y_pred = clf.predict(X_test_tfidf)
    f1 = f1_score(y_test_encoded, y_pred, average='macro')
    return f1

study_rf = optuna.create_study(direction='maximize')
study_rf.optimize(objective_rf, n_trials=50)

print("Best Random Forest params:", study_rf.best_params)
print("Best Random Forest F1 (macro):", study_rf.best_value)

[I 2025-12-30 22:58:32,643] A new study created in memory with name: no-name-db751d7e-5a39-418a-b9af-9a7d14f8b97d
[I 2025-12-30 22:58:36,352] Trial 0 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 397, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 0 with value: 0.18298476155222407.
[I 2025-12-30 22:58:37,585] Trial 1 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 244, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.18298476155222407.
[I 2025-12-30 23:01:00,705] Trial 2 finished with value: 0.6142472520048304 and parameters: {'n_estimators': 421, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 16, 'max_features': None}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:01,811] Trial 3 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 464, 'max_depth': 2, 'min_samples_split': 16, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:04,757] Trial 4 finished with value: 0.6047899567348995 and parameters: {'n_estimators': 366, 'max_depth': 26, 'min_samples_split': 3, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:23,782] Trial 5 finished with value: 0.5872200968836743 and parameters: {'n_estimators': 77, 'max_depth': 18, 'min_samples_split': 19, 'min_samples_leaf': 20, 'max_features': None}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:23,962] Trial 6 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 64, 'max_depth': 17, 'min_samples_split': 14, 'min_samples_leaf': 13, 'max_features': 'log2'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:25,973] Trial 7 finished with value: 0.5399338964423419 and parameters: {'n_estimators': 306, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 19, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:27,103] Trial 8 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 427, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 11, 'max_features': 'log2'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:01:32,277] Trial 9 finished with value: 0.5999202732983052 and parameters: {'n_estimators': 400, 'max_depth': 24, 'min_samples_split': 16, 'min_samples_leaf': 11, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.6142472520048304.
[I 2025-12-30 23:03:19,566] Trial 10 finished with value: 0.6275764368380152 and parameters: {'n_estimators': 209, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 10 with value: 0.6275764368380152.
[I 2025-12-30 23:05:07,536] Trial 11 finished with value: 0.631375844089216 and parameters: {'n_estimators': 196, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 11 with value: 0.631375844089216.
[I 2025-12-30 23:06:39,971] Trial 12 finished with value: 0.631563804600075 and parameters: {'n_estimators': 170, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:07:46,784] Trial 13 finished with value: 0.6140469535570773 and parameters: {'n_estimators': 159, 'max_depth': 23, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:08:40,007] Trial 14 finished with value: 0.5991640053962706 and parameters: {'n_estimators': 149, 'max_depth': 21, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:09:44,157] Trial 15 finished with value: 0.617129826759141 and parameters: {'n_estimators': 151, 'max_depth': 27, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:11:54,888] Trial 16 finished with value: 0.613667797369799 and parameters: {'n_estimators': 312, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:13:11,591] Trial 17 finished with value: 0.60171919272364 and parameters: {'n_estimators': 211, 'max_depth': 21, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:13:54,775] Trial 18 finished with value: 0.6094758755672637 and parameters: {'n_estimators': 113, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:15:34,389] Trial 19 finished with value: 0.6049776449667901 and parameters: {'n_estimators': 256, 'max_depth': 21, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:15:35,238] Trial 20 finished with value: 0.3580702241568159 and parameters: {'n_estimators': 210, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:17:15,833] Trial 21 finished with value: 0.627553119819949 and parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:18:40,732] Trial 22 finished with value: 0.6201524368916339 and parameters: {'n_estimators': 176, 'max_depth': 30, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:19:38,459] Trial 23 finished with value: 0.6258017421278773 and parameters: {'n_estimators': 114, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:21:49,248] Trial 24 finished with value: 0.6200201899069181 and parameters: {'n_estimators': 289, 'max_depth': 27, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:23:15,931] Trial 25 finished with value: 0.6062318176426463 and parameters: {'n_estimators': 232, 'max_depth': 23, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:24:13,528] Trial 26 finished with value: 0.6277546761927756 and parameters: {'n_estimators': 118, 'max_depth': 30, 'min_samples_split': 12, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:24:52,503] Trial 27 finished with value: 0.6211353561581349 and parameters: {'n_estimators': 87, 'max_depth': 28, 'min_samples_split': 13, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:25:47,652] Trial 28 finished with value: 0.6240160709562651 and parameters: {'n_estimators': 117, 'max_depth': 26, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:25:49,434] Trial 29 finished with value: 0.5270793236894932 and parameters: {'n_estimators': 341, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:25:49,903] Trial 30 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 180, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:26:57,618] Trial 31 finished with value: 0.6249403001922932 and parameters: {'n_estimators': 135, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:29:03,749] Trial 32 finished with value: 0.6240582357012983 and parameters: {'n_estimators': 259, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:30:24,947] Trial 33 finished with value: 0.6184707218398526 and parameters: {'n_estimators': 187, 'max_depth': 26, 'min_samples_split': 7, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:32:09,841] Trial 34 finished with value: 0.6213973381375353 and parameters: {'n_estimators': 230, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:32:10,117] Trial 35 finished with value: 0.2860187534219646 and parameters: {'n_estimators': 50, 'max_depth': 28, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:33:10,392] Trial 36 finished with value: 0.6071016677200884 and parameters: {'n_estimators': 167, 'max_depth': 24, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:33:52,154] Trial 37 finished with value: 0.6212594266702185 and parameters: {'n_estimators': 92, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:34:11,206] Trial 38 finished with value: 0.5646761555636899 and parameters: {'n_estimators': 135, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 15, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:34:11,784] Trial 39 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 232, 'max_depth': 29, 'min_samples_split': 18, 'min_samples_leaf': 18, 'max_features': 'log2'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:34:13,359] Trial 40 finished with value: 0.5430489738653234 and parameters: {'n_estimators': 274, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:35:56,081] Trial 41 finished with value: 0.6277559692919722 and parameters: {'n_estimators': 200, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:37:25,729] Trial 42 finished with value: 0.6208331710938729 and parameters: {'n_estimators': 199, 'max_depth': 27, 'min_samples_split': 9, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:39:04,433] Trial 43 finished with value: 0.6200202723766274 and parameters: {'n_estimators': 213, 'max_depth': 29, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:42:44,443] Trial 44 finished with value: 0.6236883025026089 and parameters: {'n_estimators': 467, 'max_depth': 30, 'min_samples_split': 12, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:43:53,976] Trial 45 finished with value: 0.6224639127620045 and parameters: {'n_estimators': 141, 'max_depth': 27, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:44:58,092] Trial 46 finished with value: 0.6080459611330451 and parameters: {'n_estimators': 166, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:44:59,352] Trial 47 finished with value: 0.18298476155222407 and parameters: {'n_estimators': 494, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 12, 'max_features': 'log2'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:45:00,300] Trial 48 finished with value: 0.6040074458068253 and parameters: {'n_estimators': 102, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 12 with value: 0.631563804600075.
[I 2025-12-30 23:46:38,774] Trial 49 finished with value: 0.6134854388186317 and parameters: {'n_estimators': 248, 'max_depth': 23, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 12 with value: 0.631563804600075.

Best Random Forest params: {'n_estimators': 170, 'max_depth': 30, 'min_samples_split': 9, 'min_samples_leaf': 1, 'max_features': None}
Best Random Forest F1 (macro): 0.631563804600075

In [36]:
# for random forest
best_params_rf = study_rf.best_params
best_f1_rf = study_rf.best_value

In [37]:
# running random forest with the best parameter values
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

best_rf = RandomForestClassifier(
    **best_params_rf,
    random_state=42
)

best_rf.fit(X_train_tfidf, y_train)

RandomForestClassifier(max_depth=30, max_features=None, min_samples_split=9,
                       n_estimators=170, random_state=42)

In [38]:
y_pred = best_rf.predict(X_test_tfidf)

rf_results = {
    "Model": "Random Forest",
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision (macro)": precision_score(y_test, y_pred, average="macro", zero_division=0),
    "Recall (macro)": recall_score(y_test, y_pred, average="macro", zero_division=0),
    "F1 Score (macro)": f1_score(y_test, y_pred, average="macro", zero_division=0),
    "Best Params": best_params_rf
}

In [39]:
results_df_rf = pd.DataFrame([rf_results])
results_df_rf

,Model,Accuracy,Precision (macro),Recall (macro),F1 Score (macro),Best Params
0,Random Forest,0.649235,0.704407,0.626505,0.631564,"{'n_estimators': 170, 'max_depth': 30, 'min_sa..."

### Xgboost hyperparamter tuning

In [40]:
from xgboost import XGBClassifier

def objective_xgb(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'max_depth': trial.suggest_int('max_depth', 2, 20),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 5),
        'use_label_encoder': False,
        'eval_metric': 'mlogloss',
        'random_state': 42
    }
    clf = XGBClassifier(**params)
    clf.fit(X_train_tfidf, y_train_encoded)
    y_pred = clf.predict(X_test_tfidf)
    f1 = f1_score(y_test_encoded, y_pred, average='macro')
    return f1

study_xgb = optuna.create_study(direction='maximize')
study_xgb.optimize(objective_xgb, n_trials=35)

print("Best XGBoost params:", study_xgb.best_params)
print("Best XGBoost F1 (macro):", study_xgb.best_value)

[I 2025-12-30 23:51:47,823] A new study created in memory with name: no-name-c97ffc9f-ef0e-458b-ace2-f1d68fdf0765
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:51:48] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:54:41,901] Trial 0 finished with value: 0.68961074725505 and parameters: {'n_estimators': 439, 'max_depth': 15, 'learning_rate': 0.022098697493506077, 'subsample': 0.6414068539744321, 'colsample_bytree': 0.7715881535448148, 'gamma': 1.0670051264780767}. Best is trial 0 with value: 0.68961074725505.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:54:41] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:55:08,584] Trial 1 finished with value: 0.6839428669570365 and parameters: {'n_estimators': 149, 'max_depth': 10, 'learning_rate': 0.22425962022768767, 'subsample': 0.5181877821810488, 'colsample_bytree': 0.6306235918412119, 'gamma': 0.27174580496555245}. Best is trial 0 with value: 0.68961074725505.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:55:08] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:55:40,786] Trial 2 finished with value: 0.6935800414262827 and parameters: {'n_estimators': 368, 'max_depth': 18, 'learning_rate': 0.18267199971302653, 'subsample': 0.8709800803759913, 'colsample_bytree': 0.8842690097395552, 'gamma': 3.145187425776758}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:55:40] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:56:56,482] Trial 3 finished with value: 0.6874296644855824 and parameters: {'n_estimators': 493, 'max_depth': 9, 'learning_rate': 0.12977058122941768, 'subsample': 0.6229008465164004, 'colsample_bytree': 0.590348855005452, 'gamma': 0.07941942606587538}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:56:56] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:57:23,118] Trial 4 finished with value: 0.6868865960471001 and parameters: {'n_estimators': 418, 'max_depth': 4, 'learning_rate': 0.21655499697119754, 'subsample': 0.794765445880095, 'colsample_bytree': 0.9080548114762719, 'gamma': 2.6049525494530714}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:57:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:57:45,228] Trial 5 finished with value: 0.6832219185038543 and parameters: {'n_estimators': 402, 'max_depth': 14, 'learning_rate': 0.15912968527249846, 'subsample': 0.9813774047365964, 'colsample_bytree': 0.8532904642792187, 'gamma': 4.538299380868103}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:57:45] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:59:12,985] Trial 6 finished with value: 0.6507167215762061 and parameters: {'n_estimators': 170, 'max_depth': 11, 'learning_rate': 0.02036109739405716, 'subsample': 0.840232156969832, 'colsample_bytree': 0.8629695876774661, 'gamma': 0.5155075191803266}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:59:13] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-30 23:59:39,952] Trial 7 finished with value: 0.6859809725995197 and parameters: {'n_estimators': 486, 'max_depth': 4, 'learning_rate': 0.11957223994288049, 'subsample': 0.6250947200922654, 'colsample_bytree': 0.5682709786687627, 'gamma': 0.8387245306540614}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [23:59:39] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:00:31,263] Trial 8 finished with value: 0.6797097488317269 and parameters: {'n_estimators': 361, 'max_depth': 11, 'learning_rate': 0.22752375356029916, 'subsample': 0.5274456982246227, 'colsample_bytree': 0.5498218274108153, 'gamma': 0.5818461425247873}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:00:31] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:00:58,031] Trial 9 finished with value: 0.6331507010915511 and parameters: {'n_estimators': 154, 'max_depth': 11, 'learning_rate': 0.01314681201134105, 'subsample': 0.6421446049313575, 'colsample_bytree': 0.6339475238783885, 'gamma': 4.6990293131728595}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:00:58] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:02:08,735] Trial 10 finished with value: 0.6918202570021292 and parameters: {'n_estimators': 284, 'max_depth': 20, 'learning_rate': 0.05768114929963173, 'subsample': 0.9332590798090067, 'colsample_bytree': 0.9804650612355593, 'gamma': 3.11385596734976}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:02:08] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:03:20,567] Trial 11 finished with value: 0.6898163306361941 and parameters: {'n_estimators': 284, 'max_depth': 20, 'learning_rate': 0.057758755370060276, 'subsample': 0.9274129061288225, 'colsample_bytree': 0.9989055713012474, 'gamma': 3.174123558290186}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:03:20] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:04:17,574] Trial 12 finished with value: 0.6913898718022008 and parameters: {'n_estimators': 293, 'max_depth': 20, 'learning_rate': 0.06371738989262868, 'subsample': 0.8843404819123174, 'colsample_bytree': 0.9794507241063458, 'gamma': 3.664660163166414}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:04:17] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:06:23,372] Trial 13 finished with value: 0.6915255178218196 and parameters: {'n_estimators': 351, 'max_depth': 17, 'learning_rate': 0.03467055859954685, 'subsample': 0.9817078991079877, 'colsample_bytree': 0.7749033139444164, 'gamma': 1.6887731082027821}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:06:23] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:06:43,274] Trial 14 finished with value: 0.6738286117044732 and parameters: {'n_estimators': 57, 'max_depth': 17, 'learning_rate': 0.08132180684302247, 'subsample': 0.7451966338342906, 'colsample_bytree': 0.9366938997807386, 'gamma': 3.590406169560073}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:06:43] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:08:13,771] Trial 15 finished with value: 0.6885737669149475 and parameters: {'n_estimators': 227, 'max_depth': 18, 'learning_rate': 0.036954564299073296, 'subsample': 0.9003511802469595, 'colsample_bytree': 0.8342859808681359, 'gamma': 2.0830438577347703}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:08:13] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:08:52,314] Trial 16 finished with value: 0.690960062502147 and parameters: {'n_estimators': 340, 'max_depth': 14, 'learning_rate': 0.11080391889275865, 'subsample': 0.7489744566176674, 'colsample_bytree': 0.6979858385135376, 'gamma': 2.8261872931883416}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:08:52] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:09:06,957] Trial 17 finished with value: 0.68654181434171 and parameters: {'n_estimators': 226, 'max_depth': 7, 'learning_rate': 0.29898478030192666, 'subsample': 0.8109029744743921, 'colsample_bytree': 0.9241902419024647, 'gamma': 4.034753880614413}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:09:07] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:10:43,789] Trial 18 finished with value: 0.6919783680384711 and parameters: {'n_estimators': 238, 'max_depth': 19, 'learning_rate': 0.03505197100986041, 'subsample': 0.9352532535103798, 'colsample_bytree': 0.801460128902626, 'gamma': 2.0690402405555166}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:10:43] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:11:59,638] Trial 19 finished with value: 0.6869007418847094 and parameters: {'n_estimators': 229, 'max_depth': 15, 'learning_rate': 0.03402707763298175, 'subsample': 0.8454395961972849, 'colsample_bytree': 0.7223068654567463, 'gamma': 1.6601950161785977}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:11:59] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:12:59,466] Trial 20 finished with value: 0.6494018163881833 and parameters: {'n_estimators': 113, 'max_depth': 18, 'learning_rate': 0.012373082823389782, 'subsample': 0.7116298661685942, 'colsample_bytree': 0.8110716362567713, 'gamma': 2.2061102501301115}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:12:59] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:14:19,466] Trial 21 finished with value: 0.6913773113514269 and parameters: {'n_estimators': 300, 'max_depth': 20, 'learning_rate': 0.044244165720227935, 'subsample': 0.9401409076881728, 'colsample_bytree': 0.8865672398218121, 'gamma': 3.1426226421862076}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:14:19] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:16:05,085] Trial 22 finished with value: 0.6791373364181094 and parameters: {'n_estimators': 248, 'max_depth': 18, 'learning_rate': 0.02454905440319392, 'subsample': 0.9412301857817297, 'colsample_bytree': 0.96486099326962, 'gamma': 3.0205818987643345}. Best is trial 2 with value: 0.6935800414262827.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:16:05] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:17:01,045] Trial 23 finished with value: 0.6957463132753681 and parameters: {'n_estimators': 314, 'max_depth': 16, 'learning_rate': 0.0799144304433713, 'subsample': 0.9975183045099689, 'colsample_bytree': 0.801073452358569, 'gamma': 2.2279858597445026}. Best is trial 23 with value: 0.6957463132753681.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:17:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:18:24,567] Trial 24 finished with value: 0.6944396279778863 and parameters: {'n_estimators': 329, 'max_depth': 13, 'learning_rate': 0.08472096321561352, 'subsample': 0.9817002256030981, 'colsample_bytree': 0.813381427376898, 'gamma': 1.4548843104688456}. Best is trial 23 with value: 0.6957463132753681.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:18:24] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:19:47,333] Trial 25 finished with value: 0.6963117501220393 and parameters: {'n_estimators': 384, 'max_depth': 13, 'learning_rate': 0.07863607292870996, 'subsample': 0.9994446907500109, 'colsample_bytree': 0.6931575068282255, 'gamma': 1.2542219351047992}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:19:47] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:20:57,939] Trial 26 finished with value: 0.6932335111968303 and parameters: {'n_estimators': 323, 'max_depth': 13, 'learning_rate': 0.0879413995333982, 'subsample': 0.992502055500783, 'colsample_bytree': 0.6873057261574553, 'gamma': 1.2692167192836323}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:20:57] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:22:29,644] Trial 27 finished with value: 0.6923529653553033 and parameters: {'n_estimators': 396, 'max_depth': 13, 'learning_rate': 0.08155015780875087, 'subsample': 0.9917328512950236, 'colsample_bytree': 0.7342126100640511, 'gamma': 1.2479552789794748}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:22:29] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:23:38,667] Trial 28 finished with value: 0.694859706531502 and parameters: {'n_estimators': 320, 'max_depth': 16, 'learning_rate': 0.09684444664285692, 'subsample': 0.9585066323762416, 'colsample_bytree': 0.6807121589153462, 'gamma': 1.4967777180516328}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:23:38] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:24:26,632] Trial 29 finished with value: 0.69166954525785 and parameters: {'n_estimators': 470, 'max_depth': 15, 'learning_rate': 0.1002654561860798, 'subsample': 0.9084472868648356, 'colsample_bytree': 0.6395244204611564, 'gamma': 2.371332825140419}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:24:26] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:26:08,555] Trial 30 finished with value: 0.6917028157068056 and parameters: {'n_estimators': 445, 'max_depth': 16, 'learning_rate': 0.07002198328664518, 'subsample': 0.9499491540891862, 'colsample_bytree': 0.5041695007538568, 'gamma': 0.8785225693584142}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:26:08] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:27:01,090] Trial 31 finished with value: 0.6958920385304923 and parameters: {'n_estimators': 320, 'max_depth': 13, 'learning_rate': 0.1404305154017203, 'subsample': 0.9657277230893349, 'colsample_bytree': 0.7574796284744891, 'gamma': 1.634602014553567}. Best is trial 25 with value: 0.6963117501220393.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:27:01] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:27:46,136] Trial 32 finished with value: 0.6990078056336602 and parameters: {'n_estimators': 384, 'max_depth': 9, 'learning_rate': 0.14432103031505297, 'subsample': 0.9636819545620402, 'colsample_bytree': 0.7665904431247078, 'gamma': 1.77936321036146}. Best is trial 32 with value: 0.6990078056336602.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:27:46] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:28:32,301] Trial 33 finished with value: 0.6923743505476091 and parameters: {'n_estimators': 385, 'max_depth': 8, 'learning_rate': 0.14011858752517262, 'subsample': 0.8639369174066744, 'colsample_bytree': 0.7654906572744596, 'gamma': 1.9173428448348206}. Best is trial 32 with value: 0.6990078056336602.
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:28:32] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-12-31 00:29:07,013] Trial 34 finished with value: 0.6925334059085215 and parameters: {'n_estimators': 362, 'max_depth': 6, 'learning_rate': 0.17717947525751726, 'subsample': 0.9047662175411073, 'colsample_bytree': 0.742433006532236, 'gamma': 1.7954467625200208}. Best is trial 32 with value: 0.6990078056336602.

Best XGBoost params: {'n_estimators': 384, 'max_depth': 9, 'learning_rate': 0.14432103031505297, 'subsample': 0.9636819545620402, 'colsample_bytree': 0.7665904431247078, 'gamma': 1.77936321036146}
Best XGBoost F1 (macro): 0.6990078056336602

In [42]:
# retrieving best parameters for XgBoost
best_params_xgb = study_xgb.best_params
best_f1_xgb = study_xgb.best_value

In [43]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

best_xgb = XGBClassifier(
    **best_params_xgb,
    use_label_encoder=False,
    eval_metric="mlogloss",
    random_state=42
)

best_xgb.fit(X_train_tfidf, y_train_encoded)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [00:33:44] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7665904431247078, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='mlogloss', feature_types=None, feature_weights=None,
              gamma=1.77936321036146, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.14432103031505297,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=9, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=384, n_jobs=None,
              num_parallel_tree=None, ...)

In [44]:
y_pred_xgb = best_xgb.predict(X_test_tfidf)

xgb_results = {
    "Model": "XGBoost",
    "Accuracy": accuracy_score(y_test_encoded, y_pred_xgb),
    "Precision (macro)": precision_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Recall (macro)": recall_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "F1 Score (macro)": f1_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Best Params": best_params_xgb
}

In [45]:
results_df_xgb = pd.DataFrame([xgb_results])
results_df_xgb

,Model,Accuracy,Precision (macro),Recall (macro),F1 Score (macro),Best Params
0,XGBoost,0.703571,0.719762,0.691895,0.699008,"{'n_estimators': 384, 'max_depth': 9, 'learnin..."

## Improving XgBoost

### finding an optimal value of max_features for Tfidf

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.feature_extraction.text import TfidfVectorizer

In [50]:
def objective_tfidf(trial):
    max_features = trial.suggest_int("max_features", 2000, 50000, step=2000)

    tfidf = TfidfVectorizer(
        max_features=max_features,
        ngram_range=(1, 2),
        min_df=3,
        max_df=0.9
    )

    X_train_vec = tfidf.fit_transform(X_train)
    X_test_vec = tfidf.transform(X_test)

    clf = LogisticRegression(
        max_iter=1000,
        n_jobs=-1,
        multi_class="auto"
    )

    clf.fit(X_train_vec, y_train_encoded)
    y_pred = clf.predict(X_test_vec)

    return f1_score(y_test_encoded, y_pred, average="macro")

In [51]:
import optuna

study_tfidf = optuna.create_study(direction="maximize")
study_tfidf.optimize(objective_tfidf, n_trials=25)

print("Best TF-IDF max_features:", study_tfidf.best_params)
print("Best macro F1:", study_tfidf.best_value)

[I 2025-12-31 00:47:12,922] A new study created in memory with name: no-name-a03f90cb-5e0d-4f1d-88ce-d1a8e3fcdbfc
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:17,955] Trial 0 finished with value: 0.7033764150115435 and parameters: {'max_features': 14000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:21,375] Trial 1 finished with value: 0.7033764150115435 and parameters: {'max_features': 44000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:22,984] Trial 2 finished with value: 0.7033764150115435 and parameters: {'max_features': 10000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:25,594] Trial 3 finished with value: 0.7033764150115435 and parameters: {'max_features': 30000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:27,238] Trial 4 finished with value: 0.7033764150115435 and parameters: {'max_features': 30000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:28,712] Trial 5 finished with value: 0.7033764150115435 and parameters: {'max_features': 14000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:30,592] Trial 6 finished with value: 0.7033764150115435 and parameters: {'max_features': 10000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:31,452] Trial 7 finished with value: 0.7033553215106458 and parameters: {'max_features': 4000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:32,317] Trial 8 finished with value: 0.7033764150115435 and parameters: {'max_features': 20000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:33,193] Trial 9 finished with value: 0.7033764150115435 and parameters: {'max_features': 24000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:34,059] Trial 10 finished with value: 0.7033764150115435 and parameters: {'max_features': 42000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:34,931] Trial 11 finished with value: 0.7033764150115435 and parameters: {'max_features': 48000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:35,871] Trial 12 finished with value: 0.7033764150115435 and parameters: {'max_features': 36000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:37,212] Trial 13 finished with value: 0.7033764150115435 and parameters: {'max_features': 48000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:38,473] Trial 14 finished with value: 0.7033764150115435 and parameters: {'max_features': 18000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:39,188] Trial 15 finished with value: 0.6991446496434142 and parameters: {'max_features': 2000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:40,072] Trial 16 finished with value: 0.7033764150115435 and parameters: {'max_features': 40000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:40,947] Trial 17 finished with value: 0.7033764150115435 and parameters: {'max_features': 26000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:41,837] Trial 18 finished with value: 0.7033764150115435 and parameters: {'max_features': 34000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:42,725] Trial 19 finished with value: 0.7033764150115435 and parameters: {'max_features': 20000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:43,616] Trial 20 finished with value: 0.7033764150115435 and parameters: {'max_features': 40000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:44,487] Trial 21 finished with value: 0.7033764150115435 and parameters: {'max_features': 8000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:45,349] Trial 22 finished with value: 0.7033764150115435 and parameters: {'max_features': 12000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:46,206] Trial 23 finished with value: 0.7033764150115435 and parameters: {'max_features': 16000}. Best is trial 0 with value: 0.7033764150115435.
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
[I 2025-12-31 00:47:47,067] Trial 24 finished with value: 0.7031419538032783 and parameters: {'max_features': 6000}. Best is trial 0 with value: 0.7033764150115435.

Best TF-IDF max_features: {'max_features': 14000}
Best macro F1: 0.7033764150115435

In [52]:
tfidf_results = {
    "best_max_features": study_tfidf.best_params["max_features"],
    "best_macro_f1": study_tfidf.best_value
}

In [70]:
vectorizer2 = TfidfVectorizer(max_features=30000)
X_train_tfidf2 = vectorizer2.fit_transform(X_train)
X_test_tfidf2 = vectorizer2.transform(X_test)

In [71]:
# training XgBoost with the best params and the most optimal max_features values
best_xgb = XGBClassifier(
    **best_params_xgb,
    use_label_encoder=False,
    eval_metric="mlogloss",
    random_state=42
)

best_xgb.fit(X_train_tfidf2, y_train_encoded)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:199: UserWarning: [01:07:53] WARNING: /workspace/src/learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7665904431247078, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='mlogloss', feature_types=None, feature_weights=None,
              gamma=1.77936321036146, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.14432103031505297,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=9, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=384, n_jobs=None,
              num_parallel_tree=None, ...)

In [72]:
y_pred_xgb = best_xgb.predict(X_test_tfidf2)

xgb_results = {
    "Model": "XGBoost",
    "Accuracy": accuracy_score(y_test_encoded, y_pred_xgb),
    "Precision (macro)": precision_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Recall (macro)": recall_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "F1 Score (macro)": f1_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Best Params": best_params_xgb
}

In [73]:
results_df_xgb2 = pd.DataFrame([xgb_results])
results_df_xgb2

,Model,Accuracy,Precision (macro),Recall (macro),F1 Score (macro),Best Params
0,XGBoost,0.703571,0.719762,0.691895,0.699008,"{'n_estimators': 384, 'max_depth': 9, 'learnin..."

In [75]:
results_df_xgb["Best Params"].values

array([{'n_estimators': 384, 'max_depth': 9, 'learning_rate': 0.14432103031505297, 'subsample': 0.9636819545620402, 'colsample_bytree': 0.7665904431247078, 'gamma': 1.77936321036146}],
      dtype=object)

In [76]:
# tfidf with max_features=14000
vectorizer3 = TfidfVectorizer(max_features=14000)
X_train2 = vectorizer3.fit_transform(X_train)
X_test2 = vectorizer3.transform(X_test)

In [78]:
xgboost3 = xgb_final = XGBClassifier(
    n_estimators=384,
    max_depth=9,
    learning_rate=0.14432103031505297,
    subsample=0.9636819545620402,
    colsample_bytree=0.7665904431247078,
    gamma=1.77936321036146,
    objective="multi:softmax",
    num_class=3,
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1
)

xgboost3.fit(X_train2, y_train_encoded)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.7665904431247078, device=None,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric='mlogloss', feature_types=None, feature_weights=None,
              gamma=1.77936321036146, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.14432103031505297,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=9, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=384, n_jobs=-1, num_class=3, ...)

In [79]:
y_pred_xgb = xgboost3.predict(X_test2)

xgb_results = {
    "Model": "XGBoost",
    "Accuracy": accuracy_score(y_test_encoded, y_pred_xgb),
    "Precision (macro)": precision_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Recall (macro)": recall_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "F1 Score (macro)": f1_score(y_test_encoded, y_pred_xgb, average="macro", zero_division=0),
    "Best Params": best_params_xgb
}

In [80]:
results_df_xgb2 = pd.DataFrame([xgb_results])
results_df_xgb2

,Model,Accuracy,Precision (macro),Recall (macro),F1 Score (macro),Best Params
0,XGBoost,0.703571,0.719762,0.691895,0.699008,"{'n_estimators': 384, 'max_depth': 9, 'learnin..."